### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by mschroederi** [hpi-bp1819-naumann/deequ#14]
return `None` instead of throwing an Exception

**Comment by janwestphal306** [comment]
Just return `None` if `result.next()` fails, does not solve the problem. Because `null` is considered a result.
Also if you call e.g. `result.getDouble(...)` the returned value will be `0.0`, even though it should be `null`.
Therefore you need to call `result.wasNull()` after requesting information from the result.

Like so:

`if (result.next()) {
    val col_min = result.getDouble("col_min")
    if (!result.wasNull()) {
      Some(MinState(col_min))
    }
  }
  None`
